# Generated by Django 2.2.3 on 2019-07-06 08:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthKit', '0002_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='aadharNumber',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=50, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aadharNumber',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Phone Number'),
        ),
    ]
